### ISSUE TITLE
Constrain keep import order with hook and CI

### ISSUE THREAD

**Issue by item4** [clicheio/cliche#102]
Use [import-order](https://github.com/spoqa/import-order), we can enforce import order.

just install and run `import-order cliche`.

I think we use it in git commit hook and CI

**Comment by miaekim** [comment]
I think that we can use [this](https://github.com/spoqa/import-order)
However, this doesn't looks stable yet.

**Comment by item4** [comment]
Oops, I make wrong link markup. I fix it.

@miaekim I used it. but have no problem (without relative path problem). I think we can use it now. If we find some bug, @dahlia will fix it. (???)

**Comment by miaekim** [comment]
okay :)
you can make new pr
