### ISSUE TITLE
what does `report_task_failure` do?

### ISSUE THREAD

**Issue by miaekim** [clicheio/cliche#103]
```python
@task_failure.connect
def report_task_failure(task_id, exception, args, kwargs, traceback, einfo):
    client = get_raven_client()
    client.captureException(einfo.exc_info)
```
When I run celery, celery shows error message because of this code.
I changed code like this, and the error doesn't show again.
```python
@task_failure.connect
def report_task_failure(task_id, exception, args, kwargs,
                        traceback, einfo, sender, signal):
    client = get_raven_client()
    client.captureException(einfo.exc_info)
```
But I cannot still understand why we use `report_task_failure`.
It shows `exc_info`, but I cannot use additional argument sender and signal.

**Comment by item4** [comment]
I think it can use `**kwargs`

**Comment by miaekim** [comment]
@item4 but `report_task_failure` is used like `report_task_failure(sender=sender)`, `report_task_failure(signal=INFO)`

**Comment by item4** [comment]
```pycon
>>> def func(**kwargs):
...    print(kwargs.keys())
... 
>>> func(a=1)
dict_keys(['a'])
```

@miaekim No problem.

**Comment by miaekim** [comment]
I reverted the code to initial code. It works well.... but I cannot understand why these errors occurred. If I notice same error, I will report again.
