### ISSUE TITLE
Relicensing code for reference use

### ISSUE THREAD

**Issue by tkiapril** [clicheio/cliche#117]
As the code of clicheio includes good practices, including well-thought out directory structure or templates for libraries (setuptools/cli/alembic, etc.) that could be used as a reference when building other python web projects, I would like to suggest that we repurpose (and relicense) the current code for referential usage without having to license referenced code with AGPL. I would want to ask permissions (and any ideas if wanted) from our contributors. (This wouldn't need any edits to the codebase or manual intervention, it's purely about your consent.)

**Comment by item4** [comment]
🆗 

How about re-license into MIT?

**Comment by miaekim** [comment]
I don't oppose relicensing. Go for it.

**Comment by tkiapril** [comment]
I'm not quite sure if you would want to relicense the project itself though; it can stay as AGPL, but sort of dual-licensing only for referential usage? (Well, technically we would have to define what it means if we want to be exact, but I'm not sure if you want that fine grained details.)

**Comment by miaekim** [comment]
Well, since this project is not maintained after 2015, I would switch the current license to non-AGPL. MIT also fine. This repository is more useful as a code structure than how it behaves.

**Comment by tkiapril** [comment]
I feel like it would be somewhat tedious if we would have to put license notice in all the files that we referenced these files from; I have some licenses in mind if you're okay with any of them.

* Public Domain
* [Unlicense](https://unlicense.org)
* [WTFPL](http://www.wtfpl.net)
* [Don't Be A Dick License](https://dbad-license.org)
* Beerware License, without having to retain notice in every file or keep a list of file referenced

**Comment by sjw0687** [comment]
I don't have any specific ideas on changing the license. Do as you wish~

**Comment by item4** [comment]
+1 for Public Domain

**Comment by miaekim** [comment]
whatever

**Comment by dahlia** [comment]
+1 for public domain or MIT.
