### ISSUE TITLE
Reintroducing deployment with Fabric/Invoke

### ISSUE THREAD

**Issue by tkiapril** [clicheio/cliche#88]
Invoke (by the same author as Fabric) seems to be a library for leveraging task executions, not particularly with system administration and deploying but about all-around task running. ([refer] (http://www.fabfile.org/roadmap.html#invoke-fabric-2-x-and-patchwork).) Thus, I think it would be better to utilize Fabric 2.0 when it's launched instead of using "raw" Invoke.

**Comment by dahlia** [comment]
+1 for Invoke.

**Comment by miaekim** [comment]
> Invoke is already Python 3 compatible, due to being a new codebase with few dependencies.

Invoke seems better

**Comment by tkiapril** [comment]
@miaekim: No offenses, but to clear up Invoke is a module that makes up Fabric 2.0 (which will become 3000 compatible, but has no launch date yet.) I was concerned about that Invoke is too broad (or abstract) than Fabric API.

**Comment by sjw0687** [comment]
@tkiapril: :+1: You are using and can use both for right purpose.
