### ISSUE TITLE
Upgrade to SQLAlchemy 1.0

### ISSUE THREAD

**Issue by item4** [clicheio/cliche#97]
[What's new in 1.0?](http://docs.sqlalchemy.org/en/rel_1_0/changelog/migration_10.html)

We must test with sqla 1.0 and debug it.

**Comment by item4** [comment]
I think dummy insert can use [bulk operation](http://docs.sqlalchemy.org/en/latest/orm/persistence_techniques.html#bulk-operations).

**Comment by dahlia** [comment]
+1

**Comment by miaekim** [comment]
LGTM!
[![LGTM](http://www.lgtm.in/p/et3j8f3Wp)](http://www.lgtm.in/i/et3j8f3Wp)

[:+1:](http://www.lgtm.in/u/et3j8f3Wp) [:-1:](http://www.lgtm.in/r/et3j8f3Wp)

**Comment by miaekim** [comment]
LGTM!
[![LGTM](http://www.lgtm.in/p/MEKuUqadq)](http://www.lgtm.in/i/MEKuUqadq)

[:+1:](http://www.lgtm.in/u/MEKuUqadq) [:-1:](http://www.lgtm.in/r/MEKuUqadq)

**Comment by item4** [comment]
I tried apply bulk insert. But it fail.

Step 1. I tried insert works (set of `Work`). But SA need `Work.id` and `Work.id` is relying on `Name.id`.
```pytb
sqlalchemy.exc.IntegrityError: (psycopg2.IntegrityError) null value in column "id" violates not-null constraint
```

Step 2. I tried insert names (set of `Name`) first. But SA need `Name.nameable_id` and it's relying on `Nameable.id`.
```pytb
sqlalchemy.exc.IntegrityError: (psycopg2.IntegrityError) null value in column "nameable_id" violates not-null constraint
```

Step 3. I tried insert nameables (set of `Nameable`) first. But `Nameable` have constraint about init.
```pytb
Exception: <class 'cliche.name.Nameable'> cannot be instantiated
```

Step 4. I removed event for insert and tried Step 3 again. nameables are inserted. But `Name.nameable_id` was not refreshed.
```pytb
sqlalchemy.exc.IntegrityError: (psycopg2.IntegrityError) null value in column "nameable_id" violates not-null constraint
```

I think there is no advantage with complexed tables. We would rather use sql directly than use it. :(

**Comment by dahlia** [comment]
Upgrading to SQLAlchemy 1.0 does not mean utilizing all new features introduced by SQLAlchemy 1.0.
