### ISSUE TITLE
Fix wrong import order

### ISSUE THREAD

**Issue by item4** [clicheio/cliche#98]
I tested [import-order](https://github.com/spoqa/import-order) to our source and found some wrong import order like this.

```
./deploy/scripts/upgrade-web.py:5-6: subprocess must be above than sys
5 import sys
6 import subprocess
```

I think we had better fix them.

**Comment by tkiapril** [comment]
Whoops. Not hard to fix.

**Comment by miaekim** [comment]
this issue is covered by #102. So I will close this issue.
